[package]
name = "prove"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version="1.0.188",features=["derive"] }
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
toml = "0.8.2"
uts2ts = "0.4.1"
